#!/bin/bash

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

env

# Is .docksal installed already?
if [[ -e .docksal ]]; then
  echo-red "\nThere is a .docksal directory already; not downloading\n"
  exit 1
fi

# use master as default branch?
if [[ "$1" == "" ]]; then
  BRANCH=master
else
  BRANCH=$1
fi

git clone -q --branch $BRANCH https://github.com/fjmk/docksal-template .docksal
echo-green-bg "copy .docksal/docksal.env to .docksal/docksal-local.env"

cp .docksal/docksal.env .docksal/docksal-local.env
if [ ! -d tests ]; then
  echo-green-bg "copy tests directory to PROJECT_ROOT"
  mv .docksal/tests .
fi
# add drupal8 config dir if not exists
if [[ -e config ]]; then
  echo-yellow "\nThere is a config directory already; not overriding."
else
  echo-green-bg "Create config directory in PROJECT_ROOT"
  mv .docksal/config .
fi
# add docksal alias if not exists (drush 9 installed with drupal8 composer install)
if [ ! -d drush ]; then
  echo-green-bg "Moving drush aliases to PROJECT_ROOT"
  mv .docksal/drush .
else
  if [ ! -d "drush/sites/docksal.site.yml"]; then
    echo-green-bg "copy site alias to drush directory"
    mkdir -p drush/sites
    cp .docksal/drush/sites/docksal.site.yml drush/sites/docksal.site.yml
  fi
fi
rm -rf .docksal/.git .docksal/install

echo-green ".docksal template is downloaded."
echo
echo-yellow "Probably you want to customize .docksal/docksal.env"
echo-yellow "... or .docksal/docksal-local.env"
echo
echo-yellow "Change .docksal/commands/init[-site] and .docksal/example.settings.local.php if needed."
echo
